Bump argcomplete-1.10.0 to 3.2.1
Solve dependency error message on install.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.                                                                                                                                                                            
censys 2.2.9 requires argcomplete<4.0.0,>=2.0.0, but you have argcomplete 1.10.0 which is incompatible.